### Reading Data From Different Sources

In [5]:
import pandas as pd
from io import StringIO # Import StringIO to convert a string into a file-like object because pandas.read_json() normally reads JSON from a file.
Data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}' # JSON data stored as a string
df=pd.read_json(StringIO(Data)) # read_json() reads JSON formatted data and converts it into a pandas DataFrame
# StringIO converts the JSON string into a file-like object so pandas can read it

In [6]:
df

,employee_name,email,job_profile
0,James,james@gmail.com,"{'title1': 'Team Lead', 'title2': 'Sr. Develop..."

In [10]:
df.to_json() # # Convert DataFrame to JSON format where each column contains index-value pairs.

'{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [ ]:
df.to_json(orient='index')
# Convert DataFrame to JSON where each row index contains its column as key-value pairs

'{"0":{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [ ]:
df.to_json(orient='records')
# Convert DataFrame to JSON as a list of row dictionaries (records format)

'[{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}]'

In [13]:
df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data",header=None)
# Read CSV dataset from a URL and convert it into a pandas DataFrame
# header=None is used because pandas by default treats the first row as column names.
# This dataset does not contain column headers, so we set header=None.

In [14]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [ ]:
df.to_csv("wine.csv") ## Save the DataFrame into a CSV file named 'wine.csv'

# Summary:
* pip install -> used in terminal (best for VS Code users)
* !pip install -> used in Jupyter to run system commands
* %pip install -> IPython magic command used in Jupyter for safer installation . This is recommended in Jupyter because it avoids installing packages in the wrong environment.

In [16]:
%pip install lxml

Requirement already satisfied: lxml in c:\users\admin\anaconda3\lib\site-packages (5.3.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
!pip install html5lib # Install html5lib library which is used for reading and processing HTML documents.
!pip install beautifulsoup4 # Install BeautifulSoup library which is used to parse and extract data from HTML or XML (commonly used in web scraping).

Requirement already satisfied: html5lib in c:\users\admin\anaconda3\lib\site-packages (1.1)
Requirement already satisfied: six>=1.9 in c:\users\admin\appdata\roaming\python\python313\site-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in c:\users\admin\anaconda3\lib\site-packages (from html5lib) (0.5.1)
Requirement already satisfied: beautifulsoup4 in c:\users\admin\anaconda3\lib\site-packages (4.13.5)
Requirement already satisfied: soupsieve>1.2 in c:\users\admin\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\admin\anaconda3\lib\site-packages (from beautifulsoup4) (4.15.0)

In [ ]:
url="https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/"

df=pd.read_html(url) # read_html() is a function of Pandas that reads all HTML tables from the webpage and store them as a list of DataFrames.

In [ ]:
df[0] ## Access the first table from the list . df[1] means 2nd table , df[3] means 3rd table....

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
1,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
2,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
3,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
4,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
5,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
6,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
7,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
8,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
9,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
10,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
11,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
12,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
13,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
14,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
15,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
16,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
17,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
18,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
19,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
20,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
21,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
22,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
23,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525
24,Seaway Bank and Trust Company,Chicago,Illinois,19328,State Bank of Texas,"January 27, 2017",10524

In [ ]:
url="https://en.wikipedia.org/wiki/Mobile_country_code"
pd.read_html(url,match="Country",header=0)[0]
# Read tables from the given webpage URL
# 'match="Country"' tells pandas to select only the table that contains the word "Country"
# 'header=0' means the first row of the table will be used as column names
# read_html() returns a list of DataFrames, so [0] selects the first matching table

,Mobile country code,Country,ISO 3166,Mobile network codes,National MNC authority,Remarks
0,289,A Abkhazia,GE-AB,List of mobile network codes in Abkhazia,NaN,MCC is not listed by ITU
1,412,Afghanistan,AF,List of mobile network codes in Afghanistan,NaN,NaN
2,276,Albania,AL,List of mobile network codes in Albania,NaN,NaN
3,603,Algeria,DZ,List of mobile network codes in Algeria,NaN,NaN
4,544,American Samoa (United States of America),AS,List of mobile network codes in American Samoa,NaN,NaN
...,...,...,...,...,...,...
247,452,Vietnam,VN,List of mobile network codes in the Vietnam,NaN,NaN
248,543,W Wallis and Futuna,WF,List of mobile network codes in Wallis and Futuna,NaN,NaN
249,421,Y Yemen,YE,List of mobile network codes in the Yemen,NaN,NaN
250,645,Z Zambia,ZM,List of mobile network codes in Zambia,NaN,NaN
251,648,Zimbabwe,ZW,List of mobile network codes in Zimbabwe,NaN,NaN

In [ ]:
!pip install openpyxl
# Install openpyxl library which is used to read and write Excel (.xlsx) files in Python.
# This library is required when working with Excel files using pandas.

Requirement already satisfied: openpyxl in c:\users\admin\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\admin\anaconda3\lib\site-packages (from openpyxl) (2.0.0)

In [ ]:
df_excel=pd.read_excel('data.xlsx') # read_excel() reads data from an Excel (.xlsx) file and converts it into a pandas DataFrame

In [ ]:
df_excel.to_pickle('df_excel')
# Save the DataFrame as a pickle file for fast storage and later use
# pandas to_pickle() method saves the DataFrame in pickle format.
# Pickle is a Python format that stores objects in a binary file.
# Advantages:
# 1. DataFrame loads very fast.
# 2. The complete Python object structure remains the same.

In [32]:
pd.read_pickle('df_excel')
# read_pickle() loads a DataFrame stored in pickle format.
# It reads the binary pickle file and reconstructs the original Python object (DataFrame).
# This method is faster than reading CSV or Excel files.

           Name  Age
0  Shwet Kamal    23
1      Aman Jha   23
2  Rishav Sinha   23
3  Roshan Singh   28